
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Links',
    description: 'Generated by Next.js and Notion',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="ko">
            <body>{children}</body>
        </html>
    )
}
